spring.application.name=supplier-service

server.port=8081

# MySQL database URL

spring.datasource.url=jdbc:mysql://localhost:3306/supplier_db
spring.datasource.username=root

# Read the password from an environment variable

spring.datasource.password=@root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka server address

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Fetch configuration during startup

spring.config.import=configserver:http://localhost:8888

# Validate tokens issued by auth-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8083/.well-known/jwks.json

# JWT audience must match Auth Service

spring.security.oauth2.resourceserver.jwt.audiences[0]=buydesk-api

# JWT signing algorithm

spring.security.oauth2.resourceserver.jwt.jws-algorithms=RS256
